import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Task Manager Solve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">
            <body
                className={`antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
