//Root Layout
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import { SettingsProvider } from "@/context/SettingsContext";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata = {
    title: "Task Manager Solve",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR">
            <body className={`antialiased`}>
                <AuthProvider>
                    <ThemeProvider>
                        <SettingsProvider>
                            {children}
                            <Toaster />
                        </SettingsProvider>
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
